### ISSUE TITLE
comma missing error

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/libo#16]
9/10 times the problem with an expression is a missing comma -- it would be *really really really* useful to have an error message that tells you where the missing comma should be.

**Comment by equilet** [comment]
this was handled via the recent error reporting branch, no?

**Comment by maccallum** [comment]
This is certainly useful, however pretty difficult with a context free grammar. I'm going to note it in a parser wishlist doc, and close this issue. @equilet, no, what was implemented was an error report if there was a trailing comma.
