### ISSUE TITLE
check if arg1 free rules with goto cleanup in assignToBundleMember

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/libo#18]
`free_arg1` should probably be initialized higher in the function --> https://github.com/CNMAT/libo/blob/master/osc_expr.c#L1853

but it's not clear to me yet, when arg1 should be freed as an atom_array

```
	cleanup:
		if(arg1 && free_arg1){
			osc_atom_array_u_free(arg1);
		}
```

**Comment by maccallum** [comment]
This is ok
