### ISSUE TITLE
safety check on free consistancy

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/libo#2]
digging around a bit, and noticed that some free functions do safety checks and others don't which sometimes makes following code conventions a little unpredictable.

```
void osc_array_free(t_osc_array *ar)
{
	if(ar){
		osc_mem_free(ar->ar);
		osc_mem_free(ar);
	}
}
```
```
void osc_atom_s_free(t_osc_atom_s *a)
{
	osc_mem_free(a);
}
```

**Comment by maccallum** [comment]
This has been reviewed and improved
