### ISSUE TITLE
make fails on OSX 10.15; libfl.a not where libo expects

### ISSUE THREAD

**Issue by wagne342** [CNMAT/libo#29]
When attempting make on OSX 10.15 one gets the following error:
'error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /usr/local/lib/libfl.a (No such file or directory)'

I think this is because 'brew install flex'  no longer writes libfl.a to this location, but rather to /usr/local/opt/flex/lib

I copied the file to the expected location and make completes.

**Comment by wagne342** [comment]
Flex version 2.6.4

**Comment by equilet** [comment]
what does `which flex` print for you?

**Comment by wagne342** [comment]
'which flex' prints /usr/local/opt/flex/bin/flex

It is also worth noting that 'brew link flex --force' returns

Warning: Refusing to link macOS provided/shadowed software: flex
If you need to have flex first in your PATH, run:
  echo 'export PATH="/usr/local/opt/flex/bin:$PATH"' >> ~/.zshrc

For compilers to find flex you may need to set:
  export LDFLAGS="-L/usr/local/opt/flex/lib"
  export CPPFLAGS="-I/usr/local/opt/flex/include"

**Comment by ramagottfried** [comment]
hi! I made this into a variable in the Makefile a while back, since I was also using Homebrew, so you can do `make FLEX_LIB_FOLDER=/usr/local/opt/flex/lib` when you call make (or edit the make file like you did) -- maybe there is a way to determine the location in the script though... that would probably be the best

**Comment by ramagottfried** [comment]
https://github.com/CNMAT/libo/blob/master/Makefile#L26

**Comment by maccallum** [comment]
I added a note about this to the bottom of the readme, but I forgot to mention the variable that you can set when you call `make`. I think that's probably the best solution, although, I usually just delete Apple's disco version of `libfl.a` and replace it with something more modern. 

I've updated the readme--feel free to reopen if this is still an issue.
