### ISSUE TITLE
linux build notes

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/libo#4]
I just ran across an issue with building libo on linux that we should put in a readme at some point -- I'll start making notes -- using this issue thread as a place holder.

The folder location our Makefile looks for Flex's libfl.a is /usr/local/lib, however if you install flex as root it will go into /usr/lib or even /usr/lib/x86_64-linux-gnu which is where it put it when I installed in on a test debian jessie virtual box.

**Comment by adrianfreed** [comment]
Yes, we caught various flavors of this at the swarmbox hack session

**Comment by maccallum** [comment]
Updated for building on all platforms
