### ISSUE TITLE
parsing large numbers append unnecessary '.' to represented number

### ISSUE THREAD

**Issue by equilet** [CNMAT/libo#9]
...When reformatting in scientific notation.
Discovered this in Max, ala o.compose.

<pre><code>
----------begin_max5_patcher----------
588.3ocyUssiaBCD8Y3q.4WKKwl6zekxpHGvIqWA1HvDksQ4euiGSRIYqp1p
cenHhS7wysy34nb12irSeRLQB9dvOB77N664gPV.uk8djd9olN9DZFQG0n6G
zSBRn6Ti3jAOYSyrXSL7qy0pZyFirWroeB1mSgmnPDUw6E.TMQpLi5.vkf3Z
Rs5x0v0IUhF8rBiY5B3.2z7hTcX6nnw3p1hrxHZXPYVVTg8gEFjVfP4zHZvy
KdpmMcBi4sAgyMB41QxVGg185Srx0roQ2oGclSiXkkgO7EaU72qUl87FL5zU
XSxehXLv3EX0buTAEC1GiuxrQwjPY3FoVslc4UH6RJtwNpEXM0f34XGFP1B5
D+nnc6tYUamXamPcv7BdLs7OYPK2vcYLIKLnxRNVgcAxEihKVLpM+efWa2IE
7up5ZfnLGR1MaRSgO4uy0h3vulZHN0kQFK25UlcoZUk31wxt2KaUgIy8lCae
hAFVj+QxDropXchtOt+NYt5AYFVdL7Xvgj3G6ZVDrqE7r8h6huucI7SKSAQn
UnxRupTuSqxhRpxDeil6zqqUrBUqSqVa92Uq4I1wWXR9qPsV7emZ8cr6yoVo
+cs5cSDXFH7ggihwIntvgB6HALP7pqyTDhakJ2VL5jQwQ4U6yQD9HbsY.VMO
hcCxoxbhyUcqXTMKwR22NFBobx7V2i+2gcXAcsetyHm5jfeTJyceQZE64.98
is6Nb2MHMgkTjX6cYofXvJ+hRqJoIUKWkNp6B3.eDtNvBAy5RdvjiLcoC4ew
+W.8AD4i
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
Fixed

**Comment by equilet** [comment]
woo hoo!
